<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Model development and selection – FeRx NLME - R package (ferx)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/10-uncertainty.html" rel="next">
<link href="../chapters/08-vpc.html" rel="prev">
<link href="../assets/ferx-favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-51776f957f81c5a6b38322b65a6a6987.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-31632d092df9090a2ed68f79c078059d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-51776f957f81c5a6b38322b65a6a6987.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6d44ada141c9df161ea2f978ad2bc43c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-93ae7541692006f28ff220a78be59d58.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-6d44ada141c9df161ea2f978ad2bc43c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo light-content"><img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo dark-content"></a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">FeRx NLME - R package (ferx)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/get-started.html"> 
<span class="menu-text">Get started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/features.html"> 
<span class="menu-text">Features</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/changelog.html"> 
<span class="menu-text">Changelog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/roadmap.html"> 
<span class="menu-text">Roadmap</span></a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/ferx-core/"> 
<span class="menu-text">ferx-core</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/ferx-book/"> 
<span class="menu-text">ferx-r</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/reference/"> 
<span class="menu-text">Reference</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/FeRx-NLME"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/FeRx-NLME/ferx-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/03-data.html">The analysis workflow</a></li><li class="breadcrumb-item"><a href="../chapters/09-model-selection.html"><span class="chapter-title">Model development and selection</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../assets/ferx-favicon.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none"><img src="../assets/ferx-favicon.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none"></a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-installation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Installing ferx</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-complete-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A complete analysis in one chapter</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">The analysis workflow</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preparing and checking the analysis dataset</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-model-files.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Writing and managing model files</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-first-fit.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Initial estimates and a first fit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-estimation-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estimation methods and controlling the fit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Diagnosing the model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-vpc.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Simulation-based evaluation: VPC</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-model-selection.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Model development and selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-uncertainty.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parameter uncertainty</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-simulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Simulating scenarios</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-tables-figures.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tables and figures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-reproducibility.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reproducibility and sharing</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Scenarios: general PK modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-structural-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structural models: analytical and ODE</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-absorption.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Absorption and bioavailability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-variability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Variability: random effects, residual error and IOV</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Scenarios: covariates</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-covariates.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Covariate modeling</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Scenarios: dosing and data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-dosing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dosing regimens and exposure metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-censoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Censored observations (BLOQ)</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Scenarios: endpoints beyond PK</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-pkpd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PK/PD and multiple endpoints</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-binary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Binary endpoints</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22-time-to-event.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Time-to-event models</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Scenarios: adaptive dosing</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/23-adaptive-dosing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Adaptive dosing and TDM strategies</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Scenarios: experimental</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/24-experimental.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Experimental features</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/25-reference.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Function, option and example index</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#where-you-are" id="toc-where-you-are" class="nav-link active" data-scroll-target="#where-you-are">Where you are</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The data</a></li>
  <li>
<a href="#comparing-fitted-models" id="toc-comparing-fitted-models" class="nav-link" data-scroll-target="#comparing-fitted-models">Comparing fitted models</a>
  <ul class="collapse">
<li><a href="#likelihood-ratio-test-and-information-criteria" id="toc-likelihood-ratio-test-and-information-criteria" class="nav-link" data-scroll-target="#likelihood-ratio-test-and-information-criteria">Likelihood ratio test and information criteria</a></li>
  <li><a href="#is-the-fit-eligible-at-all" id="toc-is-the-fit-eligible-at-all" class="nav-link" data-scroll-target="#is-the-fit-eligible-at-all">Is the fit eligible at all?</a></li>
  </ul>
</li>
  <li>
<a href="#search-configurations" id="toc-search-configurations" class="nav-link" data-scroll-target="#search-configurations">Search configurations</a>
  <ul class="collapse">
<li><a href="#the-search-space" id="toc-the-search-space" class="nav-link" data-scroll-target="#the-search-space">The search space</a></li>
  </ul>
</li>
  <li><a href="#covariate-search" id="toc-covariate-search" class="nav-link" data-scroll-target="#covariate-search">Covariate search</a></li>
  <li><a href="#structural-search" id="toc-structural-search" class="nav-link" data-scroll-target="#structural-search">Structural search</a></li>
  <li><a href="#residual-error-search" id="toc-residual-error-search" class="nav-link" data-scroll-target="#residual-error-search">Residual error search</a></li>
  <li><a href="#variability-search" id="toc-variability-search" class="nav-link" data-scroll-target="#variability-search">Variability search</a></li>
  <li><a href="#inter-occasion-variability-search" id="toc-inter-occasion-variability-search" class="nav-link" data-scroll-target="#inter-occasion-variability-search">Inter-occasion variability search</a></li>
  <li><a href="#the-whole-pipeline-at-once" id="toc-the-whole-pipeline-at-once" class="nav-link" data-scroll-target="#the-whole-pipeline-at-once">The whole pipeline at once</a></li>
  <li><a href="#tools-not-available-from-r" id="toc-tools-not-available-from-r" class="nav-link" data-scroll-target="#tools-not-available-from-r">Tools not available from R</a></li>
  <li><a href="#options-that-matter" id="toc-options-that-matter" class="nav-link" data-scroll-target="#options-that-matter">Options that matter</a></li>
  <li><a href="#pitfalls" id="toc-pitfalls" class="nav-link" data-scroll-target="#pitfalls">Pitfalls</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/FeRx-NLME/ferx-book/edit/main/chapters/09-model-selection.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FeRx-NLME/ferx-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/03-data.html">The analysis workflow</a></li><li class="breadcrumb-item"><a href="../chapters/09-model-selection.html"><span class="chapter-title">Model development and selection</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-model-selection" class="quarto-section-identifier"><span class="chapter-title">Model development and selection</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="cell" data-layout-align="center">
<div class="workflow-banner" role="note" aria-label="Workflow stage: EVALUATE">
<span class="stage">DATA</span><span class="sep"> → </span><span class="stage">MODEL</span><span class="sep"> → </span><span class="stage">ESTIMATE</span><span class="sep"> ⇄ </span><span class="stage active">EVALUATE</span><span class="sep"> → </span><span class="stage">SIMULATE</span><span class="sep"> → </span><span class="stage">REPORT</span>
</div>
</div>
<section id="where-you-are" class="level2"><h2 class="anchored" data-anchor-id="where-you-are">Where you are</h2>
<p>The base model is fitted (<a href="05-first-fit.html" class="quarto-xref"><span>Initial estimates and a first fit</span></a>) and evaluated (<a href="07-diagnostics.html" class="quarto-xref"><span>Diagnosing the model</span></a>, <a href="08-vpc.html" class="quarto-xref"><span>Simulation-based evaluation: VPC</span></a>). The diagnostics hinted at covariate relationships (<code>ETA_CL</code> correlated with <code>CRCL</code> and <code>WT</code>) and flagged autocorrelated residuals. Model development means fitting alternatives and choosing between them. You can do that by hand: write a candidate, fit it and compare. Or let ferx’s search tools generate, fit, gate and rank candidates from a search space. This chapter shows both.</p>
</section><section id="the-data" class="level2"><h2 class="anchored" data-anchor-id="the-data">The data</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">base</span> <span class="op">&lt;-</span> <span class="fu">ferx_example</span><span class="op">(</span><span class="st">"two_cpt_oral_base"</span><span class="op">)</span></span>
<span><span class="va">cov</span> <span class="op">&lt;-</span> <span class="fu">ferx_example</span><span class="op">(</span><span class="st">"two_cpt_oral_cov"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="comparing-fitted-models" class="level2"><h2 class="anchored" data-anchor-id="comparing-fitted-models">Comparing fitted models</h2>
<p><code>two_cpt_oral_cov</code> is a prespecified covariate model for the same data. Body weight scales <code>CL</code> and <code>V1</code> through a shared exponent <code>THETA_WT</code>, and creatinine clearance scales <code>CL</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/invisible.html">invisible</a></span><span class="op">(</span><span class="fu">ferx_model_get_section</span><span class="op">(</span><span class="va">cov</span><span class="op">$</span><span class="va">model</span>, <span class="st">"individual_parameters"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # [individual_parameters]</span></span>
<span><span class="co">#&gt;   CL = TVCL * (WT / 70)^THETA_WT * (CRCL / 100)^THETA_CRCL * exp(ETA_CL)</span></span>
<span><span class="co">#&gt;   V1 = TVV1 * (WT / 70)^THETA_WT * exp(ETA_V1)</span></span>
<span><span class="co">#&gt;   Q  = TVQ  * exp(ETA_Q)</span></span>
<span><span class="co">#&gt;   V2 = TVV2 * exp(ETA_V2)</span></span>
<span><span class="co">#&gt;   KA = TVKA * exp(ETA_KA)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_base</span> <span class="op">&lt;-</span> <span class="fu">ferx_fit</span><span class="op">(</span><span class="va">base</span><span class="op">$</span><span class="va">model</span>, <span class="va">base</span><span class="op">$</span><span class="va">data</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">fit_cov</span> <span class="op">&lt;-</span> <span class="fu">ferx_fit</span><span class="op">(</span><span class="va">cov</span><span class="op">$</span><span class="va">model</span>, <span class="va">cov</span><span class="op">$</span><span class="va">data</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="likelihood-ratio-test-and-information-criteria" class="level3"><h3 class="anchored" data-anchor-id="likelihood-ratio-test-and-information-criteria">Likelihood ratio test and information criteria</h3>
<p>Both are FOCEI fits to the same data, and the base model is nested in the covariate model (fix both exponents at 0). The difference in OFV is therefore a likelihood ratio statistic, with degrees of freedom equal to the number of added parameters:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">d_ofv</span> <span class="op">&lt;-</span> <span class="va">fit_base</span><span class="op">$</span><span class="va">ofv</span> <span class="op">-</span> <span class="va">fit_cov</span><span class="op">$</span><span class="va">ofv</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">fit_cov</span><span class="op">$</span><span class="va">n_parameters</span> <span class="op">-</span> <span class="va">fit_base</span><span class="op">$</span><span class="va">n_parameters</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>d_ofv <span class="op">=</span> <span class="va">d_ofv</span>, df <span class="op">=</span> <span class="va">df</span>, p_value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="va">d_ofv</span>, <span class="va">df</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;         d_ofv            df       p_value </span></span>
<span><span class="co">#&gt; 13.9235928014  2.0000000000  0.0009473931</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For non-nested models, use information criteria. <code>fit$aic</code> and <code>fit$bic</code> are the classical AIC and BIC. <code>ferx_bic()</code> computes four BIC variants that differ in how parameters are penalised:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th><code>type</code></th>
<th>Penalty added to the OFV</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>
<code>"mixed"</code> (default)</td>
<td>random-effect parameters × log(subjects) + fixed-effect parameters × log(observations)</td>
</tr>
<tr class="even">
<td><code>"fixed"</code></td>
<td>all parameters × log(observations); equals <code>fit$bic</code>
</td>
</tr>
<tr class="odd">
<td><code>"iiv"</code></td>
<td>variance parameters × log(subjects), for comparing variability structures</td>
</tr>
<tr class="even">
<td><code>"random"</code></td>
<td>all parameters × log(subjects)</td>
</tr>
</tbody>
</table>
<div id="tbl-criteria" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-criteria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Base and covariate model compared on OFV and information criteria (lower is better).
</figcaption><div aria-describedby="tbl-criteria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">criteria</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">f</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>ofv <span class="op">=</span> <span class="va">f</span><span class="op">$</span><span class="va">ofv</span>, parameters <span class="op">=</span> <span class="va">f</span><span class="op">$</span><span class="va">n_parameters</span>, aic <span class="op">=</span> <span class="va">f</span><span class="op">$</span><span class="va">aic</span>, bic <span class="op">=</span> <span class="va">f</span><span class="op">$</span><span class="va">bic</span>,</span>
<span>    bic_mixed <span class="op">=</span> <span class="fu">ferx_bic</span><span class="op">(</span><span class="va">f</span>, <span class="st">"mixed"</span><span class="op">)</span>, bic_iiv <span class="op">=</span> <span class="fu">ferx_bic</span><span class="op">(</span><span class="va">f</span>, type <span class="op">=</span> <span class="st">"iiv"</span><span class="op">)</span>,</span>
<span>    bic_random <span class="op">=</span> <span class="fu">ferx_bic</span><span class="op">(</span><span class="va">f</span>, <span class="st">"random"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>base <span class="op">=</span> <span class="fu">criteria</span><span class="op">(</span><span class="va">fit_base</span><span class="op">)</span>, covariate <span class="op">=</span> <span class="fu">criteria</span><span class="op">(</span><span class="va">fit_cov</span><span class="op">)</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span><span class="co">#&gt;                ofv parameters      aic      bic bic_mixed  bic_iiv bic_random</span></span>
<span><span class="co">#&gt; base      -1185.40         11 -1163.40 -1122.66  -1145.69 -1168.40   -1147.99</span></span>
<span><span class="co">#&gt; covariate -1199.33         13 -1173.33 -1125.18  -1152.81 -1182.32   -1155.11</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</figure>
</div>
<p>Here the covariate model is better on every criterion.</p>
</section><section id="is-the-fit-eligible-at-all" class="level3"><h3 class="anchored" data-anchor-id="is-the-fit-eligible-at-all">Is the fit eligible at all?</h3>
<p>A converged fit can still be unfit for comparison: it may never have left its initial estimates, have a parameter at a bound, or have an ill-conditioned covariance matrix. <code>check_strictness()</code> applies such gates and returns the reasons for failure:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_strictness</span><span class="op">(</span><span class="va">fit_cov</span>, require_covariance <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; $passed</span></span>
<span><span class="co">#&gt; [1] TRUE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $failures</span></span>
<span><span class="co">#&gt; character(0)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $skipped</span></span>
<span><span class="co">#&gt; character(0)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The fit from NCA-based starting values in <a href="05-first-fit.html" class="quarto-xref"><span>Initial estimates and a first fit</span></a> converged to a much worse OFV. The gates reject it:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_nca</span> <span class="op">&lt;-</span> <span class="fu">ferx_fit</span><span class="op">(</span><span class="va">base</span><span class="op">$</span><span class="va">model</span>, <span class="va">base</span><span class="op">$</span><span class="va">data</span>, inits_from_nca <span class="op">=</span> <span class="cn">TRUE</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu">check_strictness</span><span class="op">(</span><span class="va">fit_nca</span><span class="op">)</span></span>
<span><span class="co">#&gt; $passed</span></span>
<span><span class="co">#&gt; [1] FALSE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $failures</span></span>
<span><span class="co">#&gt; [1] "condition number 1.1559e+10 exceeds 1.0000e+03"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $skipped</span></span>
<span><span class="co">#&gt; character(0)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The gates and their defaults: <code>require_converged = TRUE</code>, <code>require_covariance = FALSE</code>, <code>max_condition_number = 1000</code>, <code>max_correlation = 0.95</code>, <code>reject_on_boundary = TRUE</code> and <code>reject_init_stall = TRUE</code>. Set a threshold to <code>NULL</code>, or a flag to <code>FALSE</code>, to disable that gate. <code>reject_init_stall</code> assumes a cold start from the model file’s initial values, so turn it off when candidates start from a previous model’s estimates.</p>
</section></section><section id="search-configurations" class="level2"><h2 class="anchored" data-anchor-id="search-configurations">Search configurations</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Maturity: alpha
</div>
</div>
<div class="callout-body-container callout-body">
<p>The ferx-core pages for the search tools carry the maturity label <em>alpha</em>. See <a href="https://ferx-nlme.github.io/ferx-core/maturity.html">feature maturity</a>.</p>
</div>
</div>
<p>The search tools read a <strong><code>.ferxsearch</code></strong> configuration file (TOML) that names the base model and data and states the search. Four bundled examples carry one as <code>$search</code>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Example</th>
<th>Search file for</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>two_cpt_oral_base</code></td>
<td>covariate search (<code>[covsearch]</code>), plus an <code>[allometry]</code> section (<a href="17-covariates.html" class="quarto-xref"><span>Covariate modeling</span></a>)</td>
</tr>
<tr class="even">
<td><code>two_cpt_oral_cov</code></td>
<td>a configuration with a BIC ranking, used here to show loading</td>
</tr>
<tr class="odd">
<td><code>warfarin</code></td>
<td>structural search (<code>[modelsearch]</code>)</td>
</tr>
<tr class="even">
<td><code>one_cpt_transit</code></td>
<td>residual error search (<code>[ruvsearch]</code>)</td>
</tr>
</tbody>
</table>
<p><code>ferx_search_config()</code> loads a file with the engine’s own strict loader, so an invalid space or a misspelt section fails before anything is fitted:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cfg</span> <span class="op">&lt;-</span> <span class="fu">ferx_search_config</span><span class="op">(</span><span class="va">base</span><span class="op">$</span><span class="va">search</span><span class="op">)</span></span>
<span><span class="va">cfg</span></span>
<span><span class="co">#&gt; &lt;ferx search configuration&gt;</span></span>
<span><span class="co">#&gt;   file:  two_cpt_oral_base.ferxsearch</span></span>
<span><span class="co">#&gt;   base:  /home/runner/work/_temp/Library/ferx/examples/search/../models/two_cpt_oral_base.ferx</span></span>
<span><span class="co">#&gt;   data:  /home/runner/work/_temp/Library/ferx/examples/search/../data/two_cpt_oral_cov.csv</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Search space (1 feature):</span></span>
<span><span class="co">#&gt;   mfl = COVARIATE?(@IIV, @CONTINUOUS, [pow, lin])</span></span>
<span><span class="co">#&gt;   COVARIATE?(@IIV,@CONTINUOUS,[pow,lin])         (exploratory)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rank: (tool default)   cutoff: (tool default)</span></span>
<span><span class="co">#&gt; Strictness (* = set by the file):</span></span>
<span><span class="co">#&gt;   * require_converged      TRUE</span></span>
<span><span class="co">#&gt;     require_covariance     FALSE</span></span>
<span><span class="co">#&gt;     max_condition_number   1000</span></span>
<span><span class="co">#&gt;     max_correlation        0.95</span></span>
<span><span class="co">#&gt;     reject_on_boundary     TRUE</span></span>
<span><span class="co">#&gt;   * reject_init_stall      TRUE</span></span>
<span><span class="co">#&gt; Run: threads = auto, retries = 2, resume = FALSE</span></span>
<span><span class="co">#&gt; Tool sections: allometry, covsearch</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The file’s sections, as shown in the printout: <code>base</code> and <code>data</code> (paths relative to the file); <code>[space]</code> with the search space as <code>mfl</code>; <code>[rank]</code> with the ranking criterion; <code>[strictness]</code> with the gates from above; <code>[run]</code> with <code>threads</code>, <code>retries</code> and <code>resume</code>; and a section per tool. The object returned holds the same information as a list:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cfg_cov</span> <span class="op">&lt;-</span> <span class="fu">ferx_search_config</span><span class="op">(</span><span class="fu">ferx_example</span><span class="op">(</span><span class="st">"two_cpt_oral_cov"</span><span class="op">)</span><span class="op">$</span><span class="va">search</span><span class="op">)</span></span>
<span><span class="va">cfg_cov</span><span class="op">$</span><span class="va">rank</span><span class="op">$</span><span class="va">type</span></span>
<span><span class="co">#&gt; [1] "bic"</span></span>
<span><span class="va">cfg</span><span class="op">$</span><span class="va">tools</span></span>
<span><span class="co">#&gt; [1] "allometry" "covsearch"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="the-search-space" class="level3"><h3 class="anchored" data-anchor-id="the-search-space">The search space</h3>
<p>The space is written in the Model Feature Language (MFL). <code>COVARIATE?(@IIV, @CONTINUOUS, [pow, lin])</code> means: every parameter with a random effect, crossed with every continuous covariate, as a power or linear effect, each optional (<code>?</code>). The <code>?</code> is accepted on four keywords only – <code>COVARIATE</code>, <code>IIV</code>, <code>IOV</code> and <code>COVARIANCE</code> – and marks that statement as something the search may decline; written without it, every candidate carries the feature. The other keywords, <code>ABSORPTION</code> and <code>PERIPHERALS</code> among them, enumerate the alternatives to try instead. The <code>@</code> symbols resolve against the model’s <code>[covariates]</code> block and its random effects, so one space travels between models: <code>@CATEGORICAL</code> selects the categorical covariates as <code>@CONTINUOUS</code> selects the continuous ones. <code>ferx_search_space()</code> parses MFL text and, given a model and data, expands the symbols into the concrete candidates:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ferx_search_space</span><span class="op">(</span><span class="st">"COVARIATE?(@IIV, @CONTINUOUS, [pow, lin])"</span><span class="op">)</span></span>
<span><span class="co">#&gt; &lt;ferx search space&gt; (as written)</span></span>
<span><span class="co">#&gt;   mfl = COVARIATE?(@IIV, @CONTINUOUS, [pow, lin])</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;                                  feature   keyword optional</span></span>
<span><span class="co">#&gt; 1 COVARIATE?(@IIV,@CONTINUOUS,[pow,lin]) COVARIATE     TRUE</span></span>
<span><span class="va">space</span> <span class="op">&lt;-</span> <span class="fu">ferx_search_space</span><span class="op">(</span><span class="va">cfg</span><span class="op">$</span><span class="va">mfl</span>, model <span class="op">=</span> <span class="va">base</span><span class="op">$</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">base</span><span class="op">$</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">space</span>, <span class="st">"covariate_effects"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 20</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">space</span>, <span class="st">"covariate_effects"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;   parameter covariate effect op optional</span></span>
<span><span class="co">#&gt; 1        CL        WT    pow  *     TRUE</span></span>
<span><span class="co">#&gt; 2        CL        WT    lin  *     TRUE</span></span>
<span><span class="co">#&gt; 3        CL      CRCL    pow  *     TRUE</span></span>
<span><span class="co">#&gt; 4        CL      CRCL    lin  *     TRUE</span></span>
<span><span class="co">#&gt; 5        V1        WT    pow  *     TRUE</span></span>
<span><span class="co">#&gt; 6        V1        WT    lin  *     TRUE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>ferx_search_coverage()</code> reports, without fitting, whether the engine can build candidates for each feature of a space:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ferx_search_coverage</span><span class="op">(</span><span class="va">space</span><span class="op">)</span></span>
<span><span class="co">#&gt;                                  feature covered reason</span></span>
<span><span class="co">#&gt; 1 COVARIATE?(@IIV,@CONTINUOUS,[pow,lin])    TRUE   &lt;NA&gt;</span></span>
<span><span class="fu">ferx_search_coverage</span><span class="op">(</span><span class="st">"ABSORPTION(SEQ-ZO-FO)"</span><span class="op">)</span></span>
<span><span class="co">#&gt;                 feature covered</span></span>
<span><span class="co">#&gt; 1 ABSORPTION(SEQ-ZO-FO)   FALSE</span></span>
<span><span class="co">#&gt;                                                                                                                                                                                                                                                                                                                       reason</span></span>
<span><span class="co">#&gt; 1 sequential zero-order-then-first-order absorption is not one input term on a standard disposition but a depot of its own, filled at a constant rate and emptied by `ka`; there is no template for it and the search does not generate one. Write it by hand — `examples/sequential_absorption.ferx` — and search around it</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sequential zero- then first-order absorption is not generated by the search. <a href="15-absorption.html" class="quarto-xref"><span>Absorption and bioavailability</span></a> shows the bundled model for it, which you can use as a base model instead.</p>
<p>An uncovered feature is not quietly dropped. Asking for one in a configuration file is an error at load, before anything is fitted, because a search that silently narrowed its space would answer a different question than the one you posed:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">uncovered</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"search-space"</span><span class="op">)</span>, <span class="st">"uncovered.ferxsearch"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/writeLines.html">writeLines</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">sub</a></span><span class="op">(</span><span class="st">'mfl = .*'</span>, <span class="st">'mfl = "ABSORPTION([FO,SEQ-ZO-FO])"'</span>, <span class="fu"><a href="https://rdrr.io/r/base/readLines.html">readLines</a></span><span class="op">(</span><span class="va">base</span><span class="op">$</span><span class="va">search</span><span class="op">)</span><span class="op">)</span>, <span class="va">uncovered</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/conditions.html">tryCatch</a></span><span class="op">(</span><span class="fu">ferx_search_config</span><span class="op">(</span><span class="va">uncovered</span><span class="op">)</span>, error <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">e</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">sub</a></span><span class="op">(</span><span class="st">".*mfl: "</span>, <span class="st">""</span>, <span class="fu"><a href="https://rdrr.io/r/base/conditions.html">conditionMessage</a></span><span class="op">(</span><span class="va">e</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "the search space asks for 1 feature ferx cannot build a candidate for:\n  - ABSORPTION(SEQ-ZO-FO): sequential zero-order-then-first-order absorption is not one input term on a standard disposition but a depot of its own, filled at a constant rate and emptied by `ka`; there is no template for it and the search does not generate one. Write it by hand — `examples/sequential_absorption.ferx` — and search around it\nSee the coverage table at https://ferx-nlme.github.io/ferx-core/tools/search.html#coverage"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>That is what <code>ferx_search_coverage()</code> is for: check a space before you file it.</p>
</section></section><section id="covariate-search" class="level2"><h2 class="anchored" data-anchor-id="covariate-search">Covariate search</h2>
<p><code>ferx_covsearch()</code> runs a stepwise covariate search. In each forward step it fits every remaining candidate effect and adds the one with the largest significant OFV drop at <code>p_forward</code>. The backward phase then removes effects whose removal is not significant at the stricter <code>p_backward</code>. The bundled configuration uses <code>p_forward = 0.01</code> and <code>p_backward = 0.001</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cs_dir</span> <span class="op">&lt;-</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"covsearch"</span><span class="op">)</span></span>
<span><span class="va">cs</span> <span class="op">&lt;-</span> <span class="fu">ferx_covsearch</span><span class="op">(</span>config <span class="op">=</span> <span class="va">base</span><span class="op">$</span><span class="va">search</span>, directory <span class="op">=</span> <span class="va">cs_dir</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">cs</span></span>
<span><span class="co">#&gt; ferx covariate search (scm-forward-then-backward)</span></span>
<span><span class="co">#&gt;   Data:  /home/runner/work/_temp/Library/ferx/examples/search/../data/two_cpt_oral_cov.csv</span></span>
<span><span class="co">#&gt;   Wrote: /tmp/Rtmpow0tXl/covsearch</span></span>
<span><span class="co">#&gt;   OFV:   -1185 (base) -&gt; -1185 (step 3)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Steps (the candidate selected at each step):</span></span>
<span><span class="co">#&gt;  step    phase parameter covariate   form  dofv  p_value converged passed</span></span>
<span><span class="co">#&gt;     1  forward        CL      CRCL linear 6.687 0.009712      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     3 backward        CL      CRCL linear 6.675 0.009776      TRUE   TRUE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; 4 candidates excluded by the strictness gate; summary() lists them.</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Final covariate relations:</span></span>
<span><span class="co">#&gt;   (none - the base model was not improved on)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The forward phase added <code>CL ~ CRCL</code> (linear) at p = 0.0097, below <code>p_forward</code>. That p-value is above <code>p_backward</code>, so the backward phase removed the effect again. The search returns the base model. Candidates excluded by the strictness gate are kept in the step table with their reason:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cs</span><span class="op">$</span><span class="va">steps</span><span class="op">[</span><span class="op">!</span><span class="va">cs</span><span class="op">$</span><span class="va">steps</span><span class="op">$</span><span class="va">passed</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"step"</span>, <span class="st">"parameter"</span>, <span class="st">"covariate"</span>, <span class="st">"form"</span>, <span class="st">"failures"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="co">#&gt;    step parameter covariate   form</span></span>
<span><span class="co">#&gt; 8     1        V1      CRCL linear</span></span>
<span><span class="co">#&gt; 20    1        KA      CRCL linear</span></span>
<span><span class="co">#&gt; 22    2        CL        WT linear</span></span>
<span><span class="co">#&gt; 38    2        KA      CRCL linear</span></span>
<span><span class="co">#&gt;                                                                                                                         failures</span></span>
<span><span class="co">#&gt; 8           condition number 8.1386e8 exceeds 1.0000e3; parameter correlation |r| = 1.0000 exceeds 0.9500 (TVKA ~ THETA_V1_CRCL)</span></span>
<span><span class="co">#&gt; 20     condition number 1.3933e10 exceeds 1.0000e3; parameter correlation |r| = 1.0000 exceeds 0.9500 (THETA_KA_CRCL ~ PROP_ERR)</span></span>
<span><span class="co">#&gt; 22          condition number 7.7525e8 exceeds 1.0000e3; parameter correlation |r| = 1.0000 exceeds 0.9500 (TVV1 ~ THETA_CL_CRCL)</span></span>
<span><span class="co">#&gt; 38 condition number 2.9288e9 exceeds 1.0000e3; parameter correlation |r| = 1.0000 exceeds 0.9500 (THETA_CL_CRCL ~ THETA_KA_CRCL)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code><a href="https://rdrr.io/r/base/print.html">print()</a></code> shows the selected step of each phase. <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> on the result adds every candidate of every step; the same table is <code>cs$steps</code>. The run directory holds the per-step journals, <code>steps.csv</code> and <code>final.ferx</code>. <code>ferx_search_results()</code> reads the step table back from disk:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span><span class="op">(</span><span class="va">cs_dir</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "backward-3" "base"       "final.ferx" "forward-1"  "forward-2" </span></span>
<span><span class="co">#&gt; [6] "steps.csv"</span></span>
<span><span class="va">steps</span> <span class="op">&lt;-</span> <span class="fu">ferx_search_results</span><span class="op">(</span><span class="va">cs_dir</span>, type <span class="op">=</span> <span class="st">"steps"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">steps</span>, <span class="st">"tool"</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "covsearch"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The search can also be stated inline. Here it is restricted to <code>CL</code>, with a less strict backward level:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cs_cl</span> <span class="op">&lt;-</span> <span class="fu">ferx_covsearch</span><span class="op">(</span>model <span class="op">=</span> <span class="va">base</span><span class="op">$</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">base</span><span class="op">$</span><span class="va">data</span>,</span>
<span>                        search_space <span class="op">=</span> <span class="st">"COVARIATE?(CL, [WT, CRCL], [pow, lin])"</span>,</span>
<span>                        p_forward <span class="op">=</span> <span class="fl">0.01</span>, p_backward <span class="op">=</span> <span class="fl">0.01</span>,</span>
<span>                        directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"covsearch-cl"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">cs_cl</span><span class="op">$</span><span class="va">included</span></span>
<span><span class="co">#&gt;   parameter covariate   form         origin</span></span>
<span><span class="co">#&gt; 1        CL      CRCL linear forward step 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>base_ofv <span class="op">=</span> <span class="va">cs_cl</span><span class="op">$</span><span class="va">base_ofv</span>, final_ofv <span class="op">=</span> <span class="va">cs_cl</span><span class="op">$</span><span class="va">final_ofv</span><span class="op">)</span></span>
<span><span class="co">#&gt;  base_ofv final_ofv </span></span>
<span><span class="co">#&gt; -1185.423 -1192.110</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The selected covariate model depends on the search space and the significance levels. A search result is evidence, not a decision. The rest of <em>The analysis workflow</em> continues with the prespecified <code>two_cpt_oral_cov</code> model, which the comparison above supports.</p>
</section><section id="structural-search" class="level2"><h2 class="anchored" data-anchor-id="structural-search">Structural search</h2>
<p><code>ferx_modelsearch()</code> searches structural features: absorption, elimination, peripheral and transit compartments, and lag time. It ranks the candidates on a criterion, the mixed BIC by default. The warfarin configuration searches a peripheral compartment and a lag time:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ms_dir</span> <span class="op">&lt;-</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"modelsearch"</span><span class="op">)</span></span>
<span><span class="va">warf</span> <span class="op">&lt;-</span> <span class="fu">ferx_example</span><span class="op">(</span><span class="st">"warfarin"</span><span class="op">)</span></span>
<span><span class="va">ms</span> <span class="op">&lt;-</span> <span class="fu">ferx_modelsearch</span><span class="op">(</span>config <span class="op">=</span> <span class="va">warf</span><span class="op">$</span><span class="va">search</span>, directory <span class="op">=</span> <span class="va">ms_dir</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">ms</span></span>
<span><span class="co">#&gt; ferx structural model search (reduced_stepwise, ranked on bic_mixed)</span></span>
<span><span class="co">#&gt;   Data:  /home/runner/work/_temp/Library/ferx/examples/search/../data/warfarin.csv</span></span>
<span><span class="co">#&gt;   Wrote: /tmp/Rtmpow0tXl/modelsearch</span></span>
<span><span class="co">#&gt;   Base:  base - FO, 0 peripherals</span></span>
<span><span class="co">#&gt;   bic_mixed:   -261.8 (base) -&gt; -261.8 (base)</span></span>
<span><span class="co">#&gt;   5 models over 2 layers</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Ranked models (best first):</span></span>
<span><span class="co">#&gt;  rank   id              structure    ofv criterion d_criterion converged passed</span></span>
<span><span class="co">#&gt;     1 base      FO, 0 peripherals -280.4    -261.8       0.000      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     2 run1 FO, 0 peripherals, lag -282.7    -259.6       2.258      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     3 run2       FO, 1 peripheral -282.5    -254.6       7.254      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     4 run4  FO, 1 peripheral, lag -283.6    -251.1      10.730      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     5 run3  FO, 1 peripheral, lag -282.7    -250.2      11.660      TRUE   TRUE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The base structure ranks best on the mixed BIC. The lag-time model has a lower OFV, but not by enough to pay for its extra parameters. Every candidate’s model text is kept, so the runner-up can be inspected or refitted:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">runner_up</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="va">ms_dir</span>, <span class="st">"runner_up.ferx"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/writeLines.html">writeLines</a></span><span class="op">(</span><span class="va">ms</span><span class="op">$</span><span class="va">model_text</span><span class="op">[[</span><span class="st">"run1"</span><span class="op">]</span><span class="op">]</span>, <span class="va">runner_up</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/invisible.html">invisible</a></span><span class="op">(</span><span class="fu">ferx_model_get_section</span><span class="op">(</span><span class="va">runner_up</span>, <span class="st">"structural_model"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # [structural_model]</span></span>
<span><span class="co">#&gt;   pk one_cpt_oral(cl=CL, v=V, ka=KA, lagtime=ALAG)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>With <code>resume = TRUE</code> and the same <code>directory</code>, a search reuses the fits it already journalled:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ms_again</span> <span class="op">&lt;-</span> <span class="fu">ferx_modelsearch</span><span class="op">(</span>config <span class="op">=</span> <span class="va">warf</span><span class="op">$</span><span class="va">search</span>, directory <span class="op">=</span> <span class="va">ms_dir</span>, resume <span class="op">=</span> <span class="cn">TRUE</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">ms_again</span><span class="op">$</span><span class="va">models</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"structure"</span>, <span class="st">"reused"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="co">#&gt;     id              structure reused</span></span>
<span><span class="co">#&gt; 1 base      FO, 0 peripherals   TRUE</span></span>
<span><span class="co">#&gt; 2 run1 FO, 0 peripherals, lag   TRUE</span></span>
<span><span class="co">#&gt; 3 run2       FO, 1 peripheral   TRUE</span></span>
<span><span class="co">#&gt; 4 run3  FO, 1 peripheral, lag   TRUE</span></span>
<span><span class="co">#&gt; 5 run4  FO, 1 peripheral, lag   TRUE</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="fu">ferx_search_results</span><span class="op">(</span><span class="va">ms_dir</span>, type <span class="op">=</span> <span class="st">"models"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 5</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="residual-error-search" class="level2"><h2 class="anchored" data-anchor-id="residual-error-search">Residual error search</h2>
<p><code>ferx_ruvsearch()</code> tests four families of residual error extensions against the current error model, using the likelihood ratio test at <code>p_value</code>:</p>
<ul>
<li>
<code>IIV_on_RUV</code>: a random effect on the residual error magnitude. It needs an estimation method with interaction.</li>
<li>
<code>power</code>: a proportional error raised to an estimated power.</li>
<li>
<code>combined</code>: an additive component added to the proportional one.</li>
<li>
<code>time_varying</code>: a residual error magnitude that differs below a time-after-dose cutoff, set at quantiles given by <code>groups</code>.</li>
</ul>
<p>Up to <code>max_iter</code> accepted features are stacked. The bundled configuration searches the analytic transit model <code>one_cpt_transit</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">transit</span> <span class="op">&lt;-</span> <span class="fu">ferx_example</span><span class="op">(</span><span class="st">"one_cpt_transit"</span><span class="op">)</span></span>
<span><span class="va">rs</span> <span class="op">&lt;-</span> <span class="fu">ferx_ruvsearch</span><span class="op">(</span>config <span class="op">=</span> <span class="va">transit</span><span class="op">$</span><span class="va">search</span>, directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"ruvsearch"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">rs</span></span>
<span><span class="co">#&gt; ferx residual-error search (likelihood-ratio test at p = 0.05)</span></span>
<span><span class="co">#&gt;   Data:  /home/runner/work/_temp/Library/ferx/examples/search/../data/transit_oral.csv</span></span>
<span><span class="co">#&gt;   Wrote: /tmp/Rtmpow0tXl/ruvsearch</span></span>
<span><span class="co">#&gt;   OFV:   -1063.880 (input) -&gt; -1070.083 (time_varying1-1, dOFV 6.203)</span></span>
<span><span class="co">#&gt;   2 iterations, 10 models fitted</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Candidates by iteration:</span></span>
<span><span class="co">#&gt;  iteration       feature       family   ofv      dofv p_value significant</span></span>
<span><span class="co">#&gt;          1    IIV_on_RUV   IIV_on_RUV -1064 -0.001255 1.00000       FALSE</span></span>
<span><span class="co">#&gt;          1         power        power -1066  1.896000 0.16850       FALSE</span></span>
<span><span class="co">#&gt;          1      combined     combined -1059 -5.060000 1.00000       FALSE</span></span>
<span><span class="co">#&gt;          1 time_varying1 time_varying -1070  6.203000 0.01275        TRUE</span></span>
<span><span class="co">#&gt;          1 time_varying2 time_varying -1065  0.761800 0.38280       FALSE</span></span>
<span><span class="co">#&gt;          1 time_varying3 time_varying -1064  0.036270 0.84900       FALSE</span></span>
<span><span class="co">#&gt;          2    IIV_on_RUV   IIV_on_RUV -1070 -0.001305 1.00000       FALSE</span></span>
<span><span class="co">#&gt;          2         power        power -1071  0.986500 0.32060       FALSE</span></span>
<span><span class="co">#&gt;          2      combined     combined -1061 -9.261000 1.00000       FALSE</span></span>
<span><span class="co">#&gt;  selected converged passed</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;      TRUE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt;     FALSE      TRUE   TRUE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Selected residual-error model:</span></span>
<span><span class="co">#&gt;   time_varying1  (time_varying)</span></span>
<span><span class="co">#&gt;     DV ~ proportional(PROP_ERR * (if (TAD &lt; 1.375) RUV_TV else 1.0))</span></span>
<span><span class="va">rs</span><span class="op">$</span><span class="va">final_features</span></span>
<span><span class="co">#&gt; [1] "time_varying1"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>cwres_prescreen</code> changes what those numbers are. With it on, candidates are screened against the parent’s CWRES rather than fitted to the data, which is cheaper but puts the criterion on a different scale. Two runs that differ only in that flag, everything else held equal:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ruv</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">prescreen</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">ferx_ruvsearch</span><span class="op">(</span>model <span class="op">=</span> <span class="va">transit</span><span class="op">$</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">transit</span><span class="op">$</span><span class="va">data</span>, p_value <span class="op">=</span> <span class="fl">0.05</span>, max_iter <span class="op">=</span> <span class="fl">1</span>,</span>
<span>                 retries <span class="op">=</span> <span class="fl">0</span>, cwres_prescreen <span class="op">=</span> <span class="va">prescreen</span>,</span>
<span>                 directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"ruvsearch-"</span>, <span class="va">prescreen</span><span class="op">)</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="va">rs_data</span> <span class="op">&lt;-</span> <span class="fu">ruv</span><span class="op">(</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">rs_screen</span> <span class="op">&lt;-</span> <span class="fu">ruv</span><span class="op">(</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">screened</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/startsWith.html">startsWith</a></span><span class="op">(</span><span class="va">rs_screen</span><span class="op">$</span><span class="va">candidates</span><span class="op">$</span><span class="va">id</span>, <span class="st">"cwres"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>fitted_to_data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="va">rs_data</span><span class="op">$</span><span class="va">candidates</span><span class="op">$</span><span class="va">criterion</span><span class="op">[</span><span class="va">rs_data</span><span class="op">$</span><span class="va">candidates</span><span class="op">$</span><span class="va">id</span> <span class="op">!=</span> <span class="st">"input"</span><span class="op">]</span><span class="op">)</span>,</span>
<span>      screened_on_cwres <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="va">rs_screen</span><span class="op">$</span><span class="va">candidates</span><span class="op">$</span><span class="va">criterion</span><span class="op">[</span><span class="va">screened</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;                         [,1]       [,2]</span></span>
<span><span class="co">#&gt; fitted_to_data    -1070.0829 -1058.8200</span></span>
<span><span class="co">#&gt; screened_on_cwres   236.6697   240.6815</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>selected_data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">rs_data</span><span class="op">$</span><span class="va">final_features</span><span class="op">)</span>, selected_screened <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">rs_screen</span><span class="op">$</span><span class="va">final_features</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;     selected_data selected_screened </span></span>
<span><span class="co">#&gt;                 1                 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The two sets of numbers are not comparable, and the screening rows are the ones whose <code>id</code> starts with <code>cwres</code>. Note that the cheaper pass also selected differently here, so treat prescreening as a different search rather than a faster one. The engine default is <code>cwres_prescreen = FALSE</code>, which is what the configuration run above used.</p>
<p>The search accepted a time-varying residual error in the first iteration, and nothing further in the second. The base model of this workflow, which carried a residual autocorrelation warning in <a href="07-diagnostics.html" class="quarto-xref"><span>Diagnosing the model</span></a>, can be searched the same way with the inline arguments (<code>model</code>, <code>data</code>, <code>p_value</code>, <code>max_iter</code>, …).</p>
</section><section id="variability-search" class="level2"><h2 class="anchored" data-anchor-id="variability-search">Variability search</h2>
<p><code>ferx_iivsearch()</code> decides the random-effect structure: which parameters carry an eta, and which etas share a covariance block. The space is written with <code>IIV</code> and <code>COVARIANCE</code> statements, and <code>?</code> marks what the search may decide. The bundled <code>warfarin_block_omega</code> configuration makes every PK parameter’s eta exploratory and offers a block over whichever survive:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bo</span> <span class="op">&lt;-</span> <span class="fu">ferx_example</span><span class="op">(</span><span class="st">"warfarin_block_omega"</span><span class="op">)</span></span>
<span><span class="va">iiv</span> <span class="op">&lt;-</span> <span class="fu">ferx_iivsearch</span><span class="op">(</span>config <span class="op">=</span> <span class="va">bo</span><span class="op">$</span><span class="va">search</span>, directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"iivsearch"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; Warning in .ferx_compute_cor_matrix(result$cov_matrix): One or more diagonal</span></span>
<span><span class="co">#&gt; elements are non-positive; correlation matrix may not be meaningful.</span></span>
<span><span class="va">iiv</span></span>
<span><span class="co">#&gt; ferx variability-structure search (top_down_exhaustive + block structure, ranked on bic_iiv)</span></span>
<span><span class="co">#&gt;   Data:  /home/runner/work/_temp/Library/ferx/examples/search/../data/warfarin_block_omega.csv</span></span>
<span><span class="co">#&gt;   Wrote: /tmp/Rtmpow0tXl/iivsearch</span></span>
<span><span class="co">#&gt;   Input: [ETA_CL,ETA_V]+[ETA_KA]</span></span>
<span><span class="co">#&gt;   bic_iiv:   -271.3 (input) -&gt; -272.5 (run10)</span></span>
<span><span class="co">#&gt;   12 models over 3 steps</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step 1 (no_of_etas), parent input ([ETA_CL,ETA_V]+[ETA_KA]):</span></span>
<span><span class="co">#&gt;  rank    id               structure criterion d_criterion  best</span></span>
<span><span class="co">#&gt;     1 input [ETA_CL,ETA_V]+[ETA_KA]   -271.30         0.0  TRUE</span></span>
<span><span class="co">#&gt;     2  run1       [ETA_CL]+[ETA_KA]    -14.16      -257.1 FALSE</span></span>
<span><span class="co">#&gt;     3  run5                [ETA_KA]     96.90      -368.2 FALSE</span></span>
<span><span class="co">#&gt;     4  run4                [ETA_CL]    108.60      -379.9 FALSE</span></span>
<span><span class="co">#&gt;     5  run6                 [ETA_V]    178.10      -449.4 FALSE</span></span>
<span><span class="co">#&gt;     6  run7                            181.70      -453.0 FALSE</span></span>
<span><span class="co">#&gt;    NA  run2          [ETA_CL,ETA_V]     86.80      -358.1 FALSE</span></span>
<span><span class="co">#&gt;    NA  run3        [ETA_KA]+[ETA_V]     27.38      -298.7 FALSE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step 2 (block_structure), parent input ([ETA_CL,ETA_V]+[ETA_KA]):</span></span>
<span><span class="co">#&gt;  rank    id                 structure criterion d_criterion  best</span></span>
<span><span class="co">#&gt;     1 run10   [ETA_KA,ETA_V]+[ETA_CL]    -272.5      1.1930  TRUE</span></span>
<span><span class="co">#&gt;     2  run9   [ETA_CL,ETA_KA]+[ETA_V]    -272.2      0.9037 FALSE</span></span>
<span><span class="co">#&gt;     3 input   [ETA_CL,ETA_V]+[ETA_KA]    -271.3      0.0000 FALSE</span></span>
<span><span class="co">#&gt;     4 run11     [ETA_CL,ETA_KA,ETA_V]    -269.5     -1.7740 FALSE</span></span>
<span><span class="co">#&gt;    NA  run8 [ETA_CL]+[ETA_KA]+[ETA_V]    -273.5      2.1810 FALSE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step 3 (compare_to_input), parent input ([ETA_CL,ETA_V]+[ETA_KA]):</span></span>
<span><span class="co">#&gt;  rank    id               structure criterion d_criterion  best</span></span>
<span><span class="co">#&gt;     1 run10 [ETA_KA,ETA_V]+[ETA_CL]    -272.5       1.193  TRUE</span></span>
<span><span class="co">#&gt;     2 input [ETA_CL,ETA_V]+[ETA_KA]    -271.3       0.000 FALSE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; 3 models excluded by the strictness gate; summary() lists them.</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Selected variability structure (run10):</span></span>
<span><span class="co">#&gt;   IIV:         ETA_CL, ETA_KA, ETA_V</span></span>
<span><span class="co">#&gt;   Correlated:  ETA_V ~ ETA_KA</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The printed output has three steps. The eta-count stage removes etas from the input structure – <code>top_down_exhaustive</code> tries every subset, not one deletion at a time, so the candidates include structures with two or three etas gone. The block stage then offers covariance blocks over the etas that survived. The third step, <code>compare_to_input</code>, puts the winner of the block stage back against the input structure, and it is there that the selection is made. Candidates are ranked on the BIC(iiv), which is what <code>rank = "bic"</code> means for this tool.</p>
<p>Read the printed output carefully. The input model is a candidate in its own right: the step tables rank it, and in the eta-count stage it ranks first. The strictness gate is separate from that ranking. It rejected 3 of the fitted models, and one of them reached a better criterion than the winner did:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">iiv</span><span class="op">$</span><span class="va">models</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"structure"</span>, <span class="st">"criterion"</span>, <span class="st">"rank"</span>, <span class="st">"passed"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="co">#&gt;       id                 structure  criterion rank passed</span></span>
<span><span class="co">#&gt; 1  input   [ETA_CL,ETA_V]+[ETA_KA] -271.27544   NA   TRUE</span></span>
<span><span class="co">#&gt; 2   run1         [ETA_CL]+[ETA_KA]  -14.16006    2   TRUE</span></span>
<span><span class="co">#&gt; 3   run2            [ETA_CL,ETA_V]   86.79536   NA  FALSE</span></span>
<span><span class="co">#&gt; 4   run3          [ETA_KA]+[ETA_V]   27.37871   NA  FALSE</span></span>
<span><span class="co">#&gt; 5   run4                  [ETA_CL]  108.64292    4   TRUE</span></span>
<span><span class="co">#&gt; 6   run5                  [ETA_KA]   96.89883    3   TRUE</span></span>
<span><span class="co">#&gt; 7   run6                   [ETA_V]  178.10690    5   TRUE</span></span>
<span><span class="co">#&gt; 8   run7                            181.73650    6   TRUE</span></span>
<span><span class="co">#&gt; 9   run8 [ETA_CL]+[ETA_KA]+[ETA_V] -273.45621   NA  FALSE</span></span>
<span><span class="co">#&gt; 10  run9   [ETA_CL,ETA_KA]+[ETA_V] -272.17910    2   TRUE</span></span>
<span><span class="co">#&gt; 11 run10   [ETA_KA,ETA_V]+[ETA_CL] -272.46800    1   TRUE</span></span>
<span><span class="co">#&gt; 12 run11     [ETA_CL,ETA_KA,ETA_V] -269.50116    4   TRUE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>run8</code> scores -273.46 against the selected -272.47, and is out because it did not pass. Note where that verdict lives: <code>converged</code> and <code>passed</code> are columns of the tables that report on fitted candidates – <code>$models</code> here, <code>$candidates</code> and <code>$steps</code> elsewhere – and not of the per-stage ranking summary, which ranks models those rows already judged:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">iiv</span><span class="op">$</span><span class="va">steps</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "step"        "kind"        "parent"      "id"          "criterion"  </span></span>
<span><span class="co">#&gt; [6] "d_criterion" "rank"        "best"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sets.html">intersect</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"converged"</span>, <span class="st">"passed"</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">iiv</span><span class="op">$</span><span class="va">steps</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; character(0)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The input carries no rank in the combined table above because it is the parent each stage starts from. A search result is a ranking of what passed, not proof that the winner is the best model fitted.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">iiv</span><span class="op">$</span><span class="va">final_structure</span></span>
<span><span class="co">#&gt; [1] "[ETA_KA,ETA_V]+[ETA_CL]"</span></span>
<span><span class="va">iiv</span><span class="op">$</span><span class="va">final_etas</span></span>
<span><span class="co">#&gt; [1] "ETA_CL" "ETA_KA" "ETA_V"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>With <code>algorithm = "skip"</code> the eta-count stage is left out and only the block stage runs, which is the cheap way to ask one question: should <code>CL</code> and <code>V</code> share a covariance block? Skipping the eta-count stage means naming the block stage explicitly – asking for neither is an error rather than a search with nothing left to do. The statements name parameters, not etas:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">iiv_block</span> <span class="op">&lt;-</span> <span class="fu">ferx_iivsearch</span><span class="op">(</span>model <span class="op">=</span> <span class="va">bo</span><span class="op">$</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">bo</span><span class="op">$</span><span class="va">data</span>,</span>
<span>                            search_space <span class="op">=</span> <span class="st">"COVARIANCE?(IIV, [CL, V])"</span>,</span>
<span>                            algorithm <span class="op">=</span> <span class="st">"skip"</span>,</span>
<span>                            correlation_algorithm <span class="op">=</span> <span class="st">"top_down_exhaustive"</span>,</span>
<span>                            block_retries <span class="op">=</span> <span class="fl">1</span>,</span>
<span>                            directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"iivsearch-block"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; Warning in .ferx_compute_cor_matrix(result$cov_matrix): One or more diagonal</span></span>
<span><span class="co">#&gt; elements are non-positive; correlation matrix may not be meaningful.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>input <span class="op">=</span> <span class="va">iiv_block</span><span class="op">$</span><span class="va">input_structure</span>, final <span class="op">=</span> <span class="va">iiv_block</span><span class="op">$</span><span class="va">final_structure</span><span class="op">)</span></span>
<span><span class="co">#&gt;                     input                     final </span></span>
<span><span class="co">#&gt; "[ETA_CL,ETA_V]+[ETA_KA]" "[ETA_CL,ETA_V]+[ETA_KA]"</span></span>
<span><span class="va">iiv_block</span><span class="op">$</span><span class="va">models</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"structure"</span>, <span class="st">"criterion"</span>, <span class="st">"rank"</span>, <span class="st">"passed"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="co">#&gt;      id                 structure criterion rank passed</span></span>
<span><span class="co">#&gt; 1 input   [ETA_CL,ETA_V]+[ETA_KA] -271.2754   NA   TRUE</span></span>
<span><span class="co">#&gt; 2  run1 [ETA_CL]+[ETA_KA]+[ETA_V] -273.4562   NA  FALSE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Two structures are compared here: the input’s <code>block_omega (ETA_CL, ETA_V)</code> and the diagonal alternative. The input is kept – but read why. The diagonal candidate reaches the better criterion of the two, and it is out because it fails the strictness gate. The <code>failures</code> column gives the reason:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">iiv_block</span><span class="op">$</span><span class="va">models</span>, <span class="va">failures</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">failures</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "stalled at the initial estimates: no free parameter moved more than 1% of its initial value (#751)"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>No free parameter moved more than 1% of its initial value, so <code>reject_init_stall</code> refused the fit. Whether that is the right call here depends on where the candidate started, which the printed output does not say: a candidate handed its parent’s optimum can sit still because it is already converged, which is why <code>ferx_amd()</code> turns this gate off inside its steps (below). Read a gated-out candidate as unjudged rather than as rejected on merit, and refit it yourself if it matters. A selection is only as meaningful as the gate that produced it.</p>
</section><section id="inter-occasion-variability-search" class="level2"><h2 class="anchored" data-anchor-id="inter-occasion-variability-search">Inter-occasion variability search</h2>
<p><code>ferx_iovsearch()</code> decides which parameters carry an occasion random effect. It reads the occasion column from the base model’s <code>iov_column</code>, so a model without one has nothing to search. The bundled <code>warfarin_iov</code> configuration offers a kappa on every parameter that has an eta:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">iov_ex</span> <span class="op">&lt;-</span> <span class="fu">ferx_example</span><span class="op">(</span><span class="st">"warfarin_iov"</span><span class="op">)</span></span>
<span><span class="va">iov</span> <span class="op">&lt;-</span> <span class="fu">ferx_iovsearch</span><span class="op">(</span>config <span class="op">=</span> <span class="va">iov_ex</span><span class="op">$</span><span class="va">search</span>, directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"iovsearch"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">iov</span></span>
<span><span class="co">#&gt; ferx inter-occasion variability search (same-as-iiv, ranked on bic_random)</span></span>
<span><span class="co">#&gt;   Data:  /home/runner/work/_temp/Library/ferx/examples/search/../data/warfarin_iov.csv</span></span>
<span><span class="co">#&gt;   Occasions: OCC</span></span>
<span><span class="co">#&gt;   Wrote: /tmp/Rtmpow0tXl/iovsearch</span></span>
<span><span class="co">#&gt;   Input: IIV([ETA_CL]+[ETA_KA]+[ETA_V]);IOV([KAPPA_CL])</span></span>
<span><span class="co">#&gt;   bic_random:   222 (input) -&gt; -313.9 (run5)</span></span>
<span><span class="co">#&gt;   7 models over 2 steps</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step 1 (no_of_etas), parent input:</span></span>
<span><span class="co">#&gt;  rank    id                                                           structure</span></span>
<span><span class="co">#&gt;     1  run1 IIV([ETA_CL]+[ETA_KA]+[ETA_V]);IOV([KAPPA_CL]+[KAPPA_KA]+[KAPPA_V])</span></span>
<span><span class="co">#&gt;     2  run2            IIV([ETA_CL]+[ETA_KA]+[ETA_V]);IOV([KAPPA_CL]+[KAPPA_V])</span></span>
<span><span class="co">#&gt;     3  run3           IIV([ETA_CL]+[ETA_KA]+[ETA_V]);IOV([KAPPA_CL]+[KAPPA_KA])</span></span>
<span><span class="co">#&gt;     4 input                      IIV([ETA_CL]+[ETA_KA]+[ETA_V]);IOV([KAPPA_CL])</span></span>
<span><span class="co">#&gt;  criterion d_criterion  best</span></span>
<span><span class="co">#&gt;    -311.70       533.7  TRUE</span></span>
<span><span class="co">#&gt;      32.34       189.6 FALSE</span></span>
<span><span class="co">#&gt;      69.06       152.9 FALSE</span></span>
<span><span class="co">#&gt;     222.00         0.0 FALSE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step 2 (no_of_etas), parent run1:</span></span>
<span><span class="co">#&gt;  rank   id                                                           structure</span></span>
<span><span class="co">#&gt;     1 run5         IIV([ETA_CL]+[ETA_KA]);IOV([KAPPA_CL]+[KAPPA_KA]+[KAPPA_V])</span></span>
<span><span class="co">#&gt;     2 run1 IIV([ETA_CL]+[ETA_KA]+[ETA_V]);IOV([KAPPA_CL]+[KAPPA_KA]+[KAPPA_V])</span></span>
<span><span class="co">#&gt;     3 run6                  IIV([ETA_CL]);IOV([KAPPA_CL]+[KAPPA_KA]+[KAPPA_V])</span></span>
<span><span class="co">#&gt;     4 run4          IIV([ETA_CL]+[ETA_V]);IOV([KAPPA_CL]+[KAPPA_KA]+[KAPPA_V])</span></span>
<span><span class="co">#&gt;  criterion d_criterion  best</span></span>
<span><span class="co">#&gt;     -313.9       2.183  TRUE</span></span>
<span><span class="co">#&gt;     -311.7       0.000 FALSE</span></span>
<span><span class="co">#&gt;     -303.4      -8.302 FALSE</span></span>
<span><span class="co">#&gt;     -301.3     -10.480 FALSE</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Selected variability structure (run5):</span></span>
<span><span class="co">#&gt;   IIV:  ETA_CL, ETA_KA</span></span>
<span><span class="co">#&gt;   IOV:  KAPPA_CL, KAPPA_KA, KAPPA_V</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Notes:</span></span>
<span><span class="co">#&gt;   - CL already carries a κ in the base model and is left as it is</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>distribution = "same-as-iiv"</code>, the default, declares each added kappa the way its eta is declared. The first step added kappas on <code>KA</code> and <code>V</code>; the second then found that dropping <code>ETA_V</code> improved the BIC(random) further: an IOV search can change the IIV structure, because the two are fitted together. <code>CL</code> already carries a kappa in the base model and is left as it is.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">iov</span><span class="op">$</span><span class="va">final_kappas</span></span>
<span><span class="co">#&gt; [1] "KAPPA_CL" "KAPPA_KA" "KAPPA_V"</span></span>
<span><span class="va">iov</span><span class="op">$</span><span class="va">final_structure</span></span>
<span><span class="co">#&gt; [1] "IIV([ETA_CL]+[ETA_KA]);IOV([KAPPA_CL]+[KAPPA_KA]+[KAPPA_V])"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="the-whole-pipeline-at-once" class="level2"><h2 class="anchored" data-anchor-id="the-whole-pipeline-at-once">The whole pipeline at once</h2>
<p><code>ferx_amd()</code> runs the tools above in order as one automatic model-development pipeline: structural, IIV, residual, IOV, allometry, covariates. One search space describes the whole pipeline, and the engine hands each step only the statements its tool can read. A step the space says nothing about is skipped, and says so.</p>
<p><code>ferx_amd_plan()</code> shows that plan without fitting anything, which is the cheap way to check a configuration before spending the run:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">amd_ex</span> <span class="op">&lt;-</span> <span class="fu">ferx_example</span><span class="op">(</span><span class="st">"warfarin_amd"</span><span class="op">)</span></span>
<span><span class="va">plan</span> <span class="op">&lt;-</span> <span class="fu">ferx_amd_plan</span><span class="op">(</span>config <span class="op">=</span> <span class="va">amd_ex</span><span class="op">$</span><span class="va">search</span><span class="op">)</span></span>
<span><span class="va">plan</span></span>
<span><span class="co">#&gt;   index       step        tool rerun      directory</span></span>
<span><span class="co">#&gt; 1     1 structural modelsearch FALSE 01-modelsearch</span></span>
<span><span class="co">#&gt; 2     2  iivsearch   iivsearch FALSE   02-iivsearch</span></span>
<span><span class="co">#&gt; 3     3   residual   ruvsearch FALSE   03-ruvsearch</span></span>
<span><span class="co">#&gt; 4     4  iovsearch   iovsearch FALSE   04-iovsearch</span></span>
<span><span class="co">#&gt; 5     5  allometry   allometry FALSE   05-allometry</span></span>
<span><span class="co">#&gt; 6     6 covariates   covsearch FALSE   06-covsearch</span></span>
<span><span class="co">#&gt;                                                                                                  skipped</span></span>
<span><span class="co">#&gt; 1                                                                                                   &lt;NA&gt;</span></span>
<span><span class="co">#&gt; 2                                                                                                   &lt;NA&gt;</span></span>
<span><span class="co">#&gt; 3                                                                                                   &lt;NA&gt;</span></span>
<span><span class="co">#&gt; 4 the starting model declares no `iov_column` in [fit_options], so the dataset's occasions were not read</span></span>
<span><span class="co">#&gt; 5                                                            the search space has no ALLOMETRY statement</span></span>
<span><span class="co">#&gt; 6                                                            the search space has no COVARIATE statement</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>3 of the 6 steps are already ruled out by the model and the space, and the <code>skipped</code> column says why: the model declares no <code>iov_column</code>, and the space carries no <code>ALLOMETRY</code> or <code>COVARIATE</code> statement because <code>warfarin.csv</code> has no covariate column. Running it fits the rest:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">amd</span> <span class="op">&lt;-</span> <span class="fu">ferx_amd</span><span class="op">(</span>config <span class="op">=</span> <span class="va">amd_ex</span><span class="op">$</span><span class="va">search</span>, directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"amd"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">amd</span></span>
<span><span class="co">#&gt; ferx AMD pipeline (default strategy, retries all_final)</span></span>
<span><span class="co">#&gt;   Model: /home/runner/work/_temp/Library/ferx/examples/search/../models/warfarin_amd.ferx</span></span>
<span><span class="co">#&gt;   Data:  /home/runner/work/_temp/Library/ferx/examples/search/../data/warfarin.csv</span></span>
<span><span class="co">#&gt;   Wrote: /tmp/Rtmpow0tXl/amd</span></span>
<span><span class="co">#&gt;   OFV:   -286.004 (start) -&gt; -286.004 (final, dOFV -0.000)</span></span>
<span><span class="co">#&gt;   3 of 6 steps ran, 28 models fitted, 21.4 s across the steps</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Pipeline:</span></span>
<span><span class="co">#&gt;  index       step  status criterion value_before value_after          d_value</span></span>
<span><span class="co">#&gt;      1 structural     ran bic_mixed       -267.5      -267.5  0.0000000008589</span></span>
<span><span class="co">#&gt;      2  iivsearch     ran   bic_iiv       -279.1      -279.1 -0.0000000011280</span></span>
<span><span class="co">#&gt;      3   residual     ran       ofv       -286.0      -286.0  0.0000000001716</span></span>
<span><span class="co">#&gt;      4  iovsearch skipped      &lt;NA&gt;           NA          NA               NA</span></span>
<span><span class="co">#&gt;      5  allometry skipped      &lt;NA&gt;           NA          NA               NA</span></span>
<span><span class="co">#&gt;      6 covariates skipped      &lt;NA&gt;           NA          NA               NA</span></span>
<span><span class="co">#&gt;             d_ofv candidates converged passed seconds</span></span>
<span><span class="co">#&gt;   0.0000000008589          5      TRUE   TRUE   2.328</span></span>
<span><span class="co">#&gt;  -0.0000000011280         12      TRUE   TRUE   2.027</span></span>
<span><span class="co">#&gt;   0.0000000001716          7        NA     NA  17.040</span></span>
<span><span class="co">#&gt;                NA          0        NA     NA   0.000</span></span>
<span><span class="co">#&gt;                NA          0        NA     NA   0.000</span></span>
<span><span class="co">#&gt;                NA          0        NA     NA   0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Steps that did not run:</span></span>
<span><span class="co">#&gt;   4 iovsearch    skipped: the starting model declares no `iov_column` in [fit_options], so the dataset's occasions were not read</span></span>
<span><span class="co">#&gt;   5 allometry    skipped: the search space has no ALLOMETRY statement</span></span>
<span><span class="co">#&gt;   6 covariates   skipped: the search space has no COVARIATE statement</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Selected:</span></span>
<span><span class="co">#&gt;   structural   FO, 0 peripherals</span></span>
<span><span class="co">#&gt;   iivsearch    [CL]+[KA]+[V]</span></span>
<span><span class="co">#&gt;   residual     no residual-error feature added</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Notes:</span></span>
<span><span class="co">#&gt;   - [strictness] reject_init_stall is off inside every step: the model a step is handed starts at its own optimum, where "did not leave the initial estimates" (#751) is the expected outcome rather than a failed fit. It still applies to the pipeline's own start fit, and every other gate applies throughout</span></span>
<span><span class="co">#&gt;   - the retries pass on `03-ruvsearch-retries` did not improve the fit (OFV -286.004 against -286.004); the selected model was kept</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The pipeline improved nothing: <code>warfarin_amd.ferx</code> is already the model these three steps would choose, so each step re-selected its own input and the final OFV equals the starting one. That is a useful result to see printed rather than hidden – the step table carries each step’s criterion before and after, its candidate count, the strictness verdict and its wall clock, so a step that “won” by having its siblings rejected looks different from one that found something. <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> adds every candidate of every step, and the same two tables are written to the run directory as <code>steps.csv</code> and <code>candidates.csv</code>.</p>
<p>Getting the result out of an AMD run takes a little care, because two fields both look final and are not the same thing. <code>$final_model</code> is the model <em>text</em> the pipeline ended on, written to <code>$final_model_path</code>; the fitted object is <code>$fit</code>. <code>$final_ofv</code> and <code>$d_ofv</code> give the end point and the change from the start, negative being an improvement:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>final_model <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">amd</span><span class="op">$</span><span class="va">final_model</span><span class="op">)</span>, fit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">amd</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; final_model         fit </span></span>
<span><span class="co">#&gt; "character"  "ferx_fit"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>input_ofv <span class="op">=</span> <span class="va">amd</span><span class="op">$</span><span class="va">input_ofv</span>, final_ofv <span class="op">=</span> <span class="va">amd</span><span class="op">$</span><span class="va">final_ofv</span>, d_ofv <span class="op">=</span> <span class="va">amd</span><span class="op">$</span><span class="va">d_ofv</span><span class="op">)</span></span>
<span><span class="co">#&gt;              input_ofv              final_ofv                  d_ofv </span></span>
<span><span class="co">#&gt; -286.00421950648029679 -286.00421950657749903   -0.00000000009720225</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="va">amd</span><span class="op">$</span><span class="va">final_model_path</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "final.ferx"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Each step that ran also has an entry under <code>$tools</code>, named by its position and pipeline step. Watch the naming: the entry is keyed on the pipeline step, while its <code>$directory</code> is the tool that implemented it, and the two need not agree – <code>01-structural</code> was run by <code>modelsearch</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">amd</span><span class="op">$</span><span class="va">tools</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "01-structural" "02-iivsearch"  "03-residual"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">amd</span><span class="op">$</span><span class="va">tools</span>, <span class="kw">function</span><span class="op">(</span><span class="va">step</span><span class="op">)</span> <span class="va">step</span><span class="op">$</span><span class="va">directory</span>, <span class="st">""</span><span class="op">)</span></span>
<span><span class="co">#&gt;    01-structural     02-iivsearch      03-residual </span></span>
<span><span class="co">#&gt; "01-modelsearch"   "02-iivsearch"   "03-ruvsearch"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">amd</span><span class="op">$</span><span class="va">tools</span><span class="op">[[</span><span class="st">"01-structural"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co">#&gt;  [1] "index"            "step"             "tool"             "directory"       </span></span>
<span><span class="co">#&gt;  [5] "status"           "reason"           "criterion"        "selected"        </span></span>
<span><span class="co">#&gt;  [9] "seconds"          "candidates"       "path"             "models"          </span></span>
<span><span class="co">#&gt; [13] "input_model_path" "final_model_path" "model_paths"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>An entry is a plain list, not the object the tool would return on its own: it carries what the step decided (<code>status</code>, <code>reason</code>, <code>criterion</code>, <code>selected</code>, <code>seconds</code>), its slice of the candidates, and the engine’s own table read back from the run directory. Run a tool directly when you want its fit and its own options.</p>
<p>The pipeline can also be stated inline, with a shorter order and steps left out. <code>strategy</code> chooses which steps run and in what order, and <code>ferx_amd_plan()</code> will show you each without fitting anything:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">strategies</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"default"</span>, <span class="st">"reevaluation"</span>, <span class="st">"SIR"</span>, <span class="st">"SRI"</span>, <span class="st">"RSI"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>strategy <span class="op">=</span> <span class="va">strategies</span>, order <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">strategies</span>, <span class="kw">function</span><span class="op">(</span><span class="va">s</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="fu">ferx_amd_plan</span><span class="op">(</span>model <span class="op">=</span> <span class="va">amd_ex</span><span class="op">$</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">amd_ex</span><span class="op">$</span><span class="va">data</span>,</span>
<span>                      search_space <span class="op">=</span> <span class="st">"PERIPHERALS(0..1); IIV?(@PK, exp)"</span>,</span>
<span>                      strategy <span class="op">=</span> <span class="va">s</span><span class="op">)</span><span class="op">$</span><span class="va">step</span>, collapse <span class="op">=</span> <span class="st">" -&gt; "</span><span class="op">)</span></span>
<span><span class="op">}</span>, <span class="st">""</span><span class="op">)</span>, row.names <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="co">#&gt;       strategy</span></span>
<span><span class="co">#&gt; 1      default</span></span>
<span><span class="co">#&gt; 2 reevaluation</span></span>
<span><span class="co">#&gt; 3          SIR</span></span>
<span><span class="co">#&gt; 4          SRI</span></span>
<span><span class="co">#&gt; 5          RSI</span></span>
<span><span class="co">#&gt;                                                                                                  order</span></span>
<span><span class="co">#&gt; 1                          structural -&gt; iivsearch -&gt; residual -&gt; iovsearch -&gt; allometry -&gt; covariates</span></span>
<span><span class="co">#&gt; 2 structural -&gt; iivsearch -&gt; residual -&gt; iovsearch -&gt; allometry -&gt; covariates -&gt; iivsearch -&gt; residual</span></span>
<span><span class="co">#&gt; 3                                                                  structural -&gt; iivsearch -&gt; residual</span></span>
<span><span class="co">#&gt; 4                                                                  structural -&gt; residual -&gt; iivsearch</span></span>
<span><span class="co">#&gt; 5                                                                  residual -&gt; structural -&gt; iivsearch</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>reevaluation</code> is the default order with a second iivsearch and residual pass at the end. The three-letter names are shorter pipelines, not reorderings of the same six: they run the three steps their initials spell and leave out iovsearch, allometry and covariates entirely. <code>skip</code> drops a step from whichever order was chosen; <code>retries_on</code> says when the extra perturbed-restart pass runs:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">amd_sir</span> <span class="op">&lt;-</span> <span class="fu">ferx_amd</span><span class="op">(</span>model <span class="op">=</span> <span class="va">amd_ex</span><span class="op">$</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">amd_ex</span><span class="op">$</span><span class="va">data</span>,</span>
<span>                    search_space <span class="op">=</span> <span class="st">"PERIPHERALS(0..1); IIV?(@PK, exp)"</span>,</span>
<span>                    strategy <span class="op">=</span> <span class="st">"SIR"</span>, skip <span class="op">=</span> <span class="st">"residual"</span>, retries_on <span class="op">=</span> <span class="st">"final"</span>,</span>
<span>                    retries <span class="op">=</span> <span class="fl">0</span>, directory <span class="op">=</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"amd-sir"</span><span class="op">)</span>, progress <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">amd_sir</span><span class="op">$</span><span class="va">steps</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"step"</span>, <span class="st">"status"</span>, <span class="st">"criterion"</span>, <span class="st">"candidates"</span>, <span class="st">"seconds"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="co">#&gt;         step  status criterion candidates   seconds</span></span>
<span><span class="co">#&gt; 1 structural     ran bic_mixed          2 0.3338728</span></span>
<span><span class="co">#&gt; 2  iivsearch     ran   bic_iiv          8 0.1943215</span></span>
<span><span class="co">#&gt; 3   residual skipped      &lt;NA&gt;          0 0.0000000</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="tools-not-available-from-r" class="level2"><h2 class="anchored" data-anchor-id="tools-not-available-from-r">Tools not available from R</h2>
<p>ferx-core also has a global search. It runs from the ferx command line and has no R function in the pinned ferx-r build. See the ferx-core <a href="https://ferx-nlme.github.io/ferx-core/tools/index.html">tools</a> pages.</p>
<p>A <code>.ferxsearch</code> file may still carry a section for such a tool. The loader validates section names against a fixed vocabulary, which runs ahead of what this package binds and, in the case of <code>[structsearch]</code>, ahead of the engine itself; a name outside that list is an error. The file loads, and ferx warns rather than running a search that quietly ignores part of its own configuration. Where the section can be run somewhere, the warning says where:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sections_dir</span> <span class="op">&lt;-</span> <span class="fu">book_tempdir</span><span class="op">(</span><span class="st">"search-sections"</span><span class="op">)</span></span>
<span><span class="va">unconsumed</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">section</span>, <span class="va">body</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">path</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="va">sections_dir</span>, <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"\\[|\\]"</span>, <span class="st">""</span>, <span class="va">section</span><span class="op">)</span>, <span class="st">".ferxsearch"</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/writeLines.html">writeLines</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/readLines.html">readLines</a></span><span class="op">(</span><span class="va">base</span><span class="op">$</span><span class="va">search</span><span class="op">)</span>, <span class="st">""</span>, <span class="va">section</span>, <span class="va">body</span><span class="op">)</span>, <span class="va">path</span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/conditions.html">tryCatch</a></span><span class="op">(</span><span class="fu">ferx_search_config</span><span class="op">(</span><span class="va">path</span><span class="op">)</span>, warning <span class="op">=</span> <span class="va">conditionMessage</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu">unconsumed</span><span class="op">(</span><span class="st">"[globalsearch]"</span>, <span class="st">'  algorithm = "exhaustive"'</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "ferx_search_config: [globalsearch] has no R tool in this package, so it is ignored - a search run from this file does what its other sections say. To run [globalsearch], use the `ferx globalsearch` command-line tool."</span></span>
<span><span class="fu">unconsumed</span><span class="op">(</span><span class="st">"[structsearch]"</span>, <span class="st">"  x = 1"</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "ferx_search_config: [structsearch] has no R tool in this package, so it is ignored - a search run from this file does what its other sections say."</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>[globalsearch]</code> has an engine tool behind it, so the message names <code>ferx globalsearch</code>. <code>[structsearch]</code> is accepted vocabulary with no engine module yet, so it is reported without a remediation that would name a command nobody can run.</p>
</section><section id="options-that-matter" class="level2"><h2 class="anchored" data-anchor-id="options-that-matter">Options that matter</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Function</th>
<th>Arguments</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>ferx_bic()</code></td>
<td>
<code>fit</code>, <code>type</code> (<code>"mixed"</code>, <code>"fixed"</code>, <code>"iiv"</code>, <code>"random"</code>)</td>
</tr>
<tr class="even">
<td><code>check_strictness()</code></td>
<td>
<code>fit</code>, <code>require_converged</code>, <code>require_covariance</code>, <code>max_condition_number</code>, <code>max_correlation</code>, <code>reject_on_boundary</code>, <code>reject_init_stall</code>
</td>
</tr>
<tr class="odd">
<td><code>ferx_search_config()</code></td>
<td><code>path</code></td>
</tr>
<tr class="even">
<td><code>ferx_search_space()</code></td>
<td>
<code>mfl</code> (text, config or space), <code>model</code>, <code>data</code>
</td>
</tr>
<tr class="odd">
<td><code>ferx_search_coverage()</code></td>
<td>
<code>space</code> (space, config or MFL text)</td>
</tr>
<tr class="even">
<td><code>ferx_search_results()</code></td>
<td>
<code>directory</code>, <code>partial</code> (<code>NULL</code> prefers the complete table), <code>type</code> (<code>"candidates"</code>, <code>"models"</code>, <code>"steps"</code>)</td>
</tr>
</tbody>
</table>
<p>The search functions share the entry arguments <code>model</code>, <code>data</code> and <code>config</code>; the run arguments <code>threads</code>, <code>retries</code>, <code>directory</code>, <code>resume</code> and <code>progress</code>; and, wherever candidates are ranked rather than tested, <code>search_space</code>, <code>rank</code> and <code>cutoff</code>. A search is stated either by <code>config</code> or by the inline arguments, not both:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Function</th>
<th>Search arguments</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>ferx_covsearch()</code></td>
<td>
<code>algorithm</code> (<code>"scm-forward-then-backward"</code> or <code>"scm-forward"</code>), <code>p_forward</code>, <code>p_backward</code>, <code>max_steps</code>, <code>adaptive_scope_reduction</code>
</td>
</tr>
<tr class="even">
<td><code>ferx_modelsearch()</code></td>
<td>
<code>algorithm</code> (<code>"reduced_stepwise"</code>, <code>"exhaustive_stepwise"</code>, <code>"exhaustive"</code>), <code>iiv_strategy</code> (<code>"absorption_delay"</code>, <code>"add_diagonal"</code>, <code>"no_add"</code>)</td>
</tr>
<tr class="odd">
<td><code>ferx_ruvsearch()</code></td>
<td>
<code>groups</code>, <code>p_value</code>, <code>skip</code> (families not to test), <code>max_iter</code> (1 to 3), <code>cwres_prescreen</code> (screen candidates on the parent’s CWRES before refitting)</td>
</tr>
<tr class="even">
<td><code>ferx_iivsearch()</code></td>
<td>
<code>algorithm</code> (<code>"top_down_exhaustive"</code>, <code>"bottom_up_stepwise"</code>, <code>"simultaneous_stepwise"</code>, <code>"skip"</code>), <code>correlation_algorithm</code> (the block stage: <code>"top_down_exhaustive"</code> or <code>"skip"</code>), <code>as_fullblock</code> (a bottom-up candidate blocks every eta it carries), <code>block_retries</code> (extra starts per eta in the largest block)</td>
</tr>
<tr class="odd">
<td><code>ferx_iovsearch()</code></td>
<td>
<code>column</code> (the occasion column; defaults to the model’s <code>iov_column</code>, and disagreeing with it is an error), <code>distribution</code> (<code>"same-as-iiv"</code>, <code>"disjoint"</code>, <code>"joint"</code>, <code>"explicit"</code>), <code>groups</code> (the blocks <code>"explicit"</code> names), <code>block_retries</code>
</td>
</tr>
<tr class="even">
<td>
<code>ferx_amd()</code>, <code>ferx_amd_plan()</code>
</td>
<td>
<code>strategy</code> (<code>"default"</code>, <code>"reevaluation"</code>, <code>"SIR"</code>, <code>"SRI"</code>, <code>"RSI"</code>), <code>skip</code> (steps to leave out), <code>retries_on</code> (<code>"all_final"</code>, <code>"final"</code>, <code>"skip"</code>)</td>
</tr>
</tbody>
</table>
<p>Only a <code>.ferxsearch</code> file can carry a per-tool section (<code>[modelsearch]</code>, <code>[iivsearch]</code>, <code>[covsearch]</code>, …); the inline form runs each step at its own defaults.</p>
<p><code><a href="https://rdrr.io/r/base/print.html">print()</a></code> and <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> exist for the results of all of them: <code>ferx_covsearch</code>, <code>ferx_modelsearch</code>, <code>ferx_ruvsearch</code>, <code>ferx_iivsearch</code>, <code>ferx_iovsearch</code> and <code>ferx_amd</code> objects. <code>ferx_search_config</code> and <code>ferx_search_space</code> objects have <code><a href="https://rdrr.io/r/base/print.html">print()</a></code> methods.</p>
</section><section id="pitfalls" class="level2"><h2 class="anchored" data-anchor-id="pitfalls">Pitfalls</h2>
<ul>
<li>
<strong>Keep search directories.</strong> The book writes them to a temporary directory. In a project, write them next to the analysis: they hold every candidate model, the tables and <code>final.ferx</code>, and they make <code>resume</code> possible.</li>
<li>
<strong><code>ferx_search_results()</code> needs the right <code>type</code>.</strong> The covariate and residual error searches write <code>steps.csv</code>, the structural search <code>models.csv</code>. Neither wrote a <code>candidates.csv</code> here, so the default <code>type = "candidates"</code> finds no table for these runs.</li>
<li>
<strong>Compare like with like.</strong> OFV differences and likelihood ratio tests need the same data, the same estimation method and nested models.</li>
<li>
<strong>Thresholds change the answer.</strong> Record the space, the significance levels and the criterion together with the selected model. The <code>.ferxsearch</code> file is that record.</li>
</ul></section><section id="summary" class="level2"><h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li>Compare fitted models by likelihood ratio test (nested) or with <code>fit$aic</code>, <code>fit$bic</code> and <code>ferx_bic()</code>. Gate candidates with <code>check_strictness()</code>.</li>
<li>Describe searches in <code>.ferxsearch</code> files; check them with <code>ferx_search_config()</code>, <code>ferx_search_space()</code> and <code>ferx_search_coverage()</code>.</li>
<li>Run covariate, structural and residual error searches with <code>ferx_covsearch()</code>, <code>ferx_modelsearch()</code> and <code>ferx_ruvsearch()</code>, and read their tables with <code>ferx_search_results()</code>.</li>
<li>Search the random-effect structure with <code>ferx_iivsearch()</code> and the occasion structure with <code>ferx_iovsearch()</code>; both can change the IIV structure, so read what they selected rather than only the criterion.</li>
<li>Run the whole order as one pipeline with <code>ferx_amd()</code>, after checking it with <code>ferx_amd_plan()</code>. A step the space says nothing about is skipped, and the step table says why.</li>
</ul>
<p>Next: <a href="10-uncertainty.html" class="quarto-xref"><span>Parameter uncertainty</span></a> quantifies the uncertainty of the selected covariate model.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reference
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>R help: <code>?ferx_bic</code>, <code>?check_strictness</code>, <code>?ferx_search_config</code>, <code>?ferx_search_space</code>, <code>?ferx_search_coverage</code>, <code>?ferx_search_results</code>, <code>?ferx_covsearch</code>, <code>?ferx_modelsearch</code>, <code>?ferx_ruvsearch</code>, <code>?ferx_iivsearch</code>, <code>?ferx_iovsearch</code>, <code>?ferx_amd</code>, <code>?ferx_amd_plan</code>
</li>
<li>ferx-core: <a href="https://ferx-nlme.github.io/ferx-core/tools/search.html">search configuration</a>, <a href="https://ferx-nlme.github.io/ferx-core/tools/covsearch.html">covsearch</a>, <a href="https://ferx-nlme.github.io/ferx-core/tools/modelsearch.html">modelsearch</a>, <a href="https://ferx-nlme.github.io/ferx-core/tools/ruvsearch.html">ruvsearch</a>, <a href="https://ferx-nlme.github.io/ferx-core/tools/iivsearch.html">iivsearch</a>, <a href="https://ferx-nlme.github.io/ferx-core/tools/iovsearch.html">iovsearch</a>, <a href="https://ferx-nlme.github.io/ferx-core/tools/amd.html">amd</a>, <a href="https://ferx-nlme.github.io/ferx-core/tools/index.html">tools</a>
</li>
</ul>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ferx-nlme\.github\.io\/ferx-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../chapters/08-vpc.html" class="pagination-link" aria-label="Simulation-based evaluation: VPC">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Simulation-based evaluation: VPC</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/10-uncertainty.html" class="pagination-link" aria-label="Parameter uncertainty">
        <span class="nav-page-text"><span class="chapter-title">Parameter uncertainty</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FeRx-NLME/ferx-book/edit/main/chapters/09-model-selection.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FeRx-NLME/ferx-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>