#!/usr/bin/env Rscript
# Generate chapters/25-reference.qmd: the function, option and example index.
#
# Sources, all tied to the pinned build:
#   - tools/features.csv (inventory) and tools/homes.csv (chapter of each row);
#   - the installed ferx package's Rd pages (function titles, fit slot descriptions);
#   - tools/settings-docs.csv (values and defaults of settings);
#   - ferx-core docs/maturity.qmd at ferx_core_sha (read with `git show`).
# The chapter is written as static markdown so that tools/audit.R can check it
# like any other chapter. Regenerate it after a pin bump; do not edit it by hand.
#
# Usage: LANG=en_US.UTF-8 Rscript tools/make-reference.R [path/to/ferx-core]
# (a UTF-8 locale is required, or non-ASCII characters in help pages become "?")

args <- commandArgs(trailingOnly = TRUE)
core_dir <- if (length(args) >= 1) args[1] else "../ferx-core"
pin <- yaml::read_yaml("_variables.yml")
suppressMessages(library(ferx))
if (!l10n_info()$`UTF-8`) stop("run in a UTF-8 locale, e.g. LANG=en_US.UTF-8")
stopifnot(identical(as.character(packageVersion("ferx")), pin$ferx_r_version))

features <- read.csv("tools/features.csv", stringsAsFactors = FALSE)
homes <- read.csv("tools/homes.csv", stringsAsFactors = FALSE)
inv <- merge(features, homes, by = c("kind", "name", "parent"), all.x = TRUE)
settings_docs <- read.csv("tools/settings-docs.csv", stringsAsFactors = FALSE)

# ---- chapter links ------------------------------------------------------------------
chapter_ids <- list()
for (f in list.files("chapters", pattern = "^[0-9]{2}-.*\\.qmd$", full.names = TRUE)) {
  heading <- grep("^# .*\\{#sec-[a-z-]+\\}", readLines(f, n = 5), value = TRUE)[1]
  chapter_ids[[sub("\\.qmd$", "", basename(f))]] <- sub(".*\\{#(sec-[a-z-]+)\\}.*", "\\1", heading)
}
chapter_link <- function(home) {
  vapply(home, function(h) if (is.na(h) || !nzchar(h)) "" else if (h == "index") "Preface" else
    paste0("@", chapter_ids[[h]]), character(1))
}

# ---- Rd helpers -----------------------------------------------------------------------
banned <- "\\b(NONMEM|Monolix|nlmixr2?|PsN|Pumas|Pharmpy|pyDarwin|Phoenix|NLMIXED|WinBUGS|Stan|Xpose4?)\\b"
db <- tools::Rd_db("ferx")
rd_text <- function(x) paste(unlist(lapply(x, function(e) if (is.list(e)) rd_text(e) else as.character(e))), collapse = "")
rd_tag <- function(x) attr(x, "Rd_tag") %||% ""
first_sentence <- function(x) {
  x <- gsub("\\s+", " ", trimws(x))
  x <- gsub("\\s*\\([^()]*\\b(NONMEM|Monolix|nlmixr2?|Pharmpy|Xpose4?)\\b[^()]*\\)", "", x, ignore.case = TRUE)
  protected <- gsub("\\b(e\\.g|i\\.e|vs|approx|cf)\\.", "\\1<DOT>", x)
  sentences <- gsub("<DOT>", ".", unlist(strsplit(protected, "(?<=[.!?])\\s+(?=[A-Z`(])", perl = TRUE)))
  sentences <- sentences[!grepl(banned, sentences, ignore.case = TRUE)]
  if (!length(sentences)) return("")
  out <- sentences[1]
  # ferx-r's roxygen for cov_matrix has "params ? params" (a lost multiplication sign).
  out <- sub("(params) \\? (params)", "\\1 × \\2", out)
  gsub("\\|", "\\\\|", out)
}
# Help-page titles that name other software lose that word (ferx-only rule).
clean_title <- function(x) {
  x <- gsub("\\b(NONMEM|Monolix|nlmixr2?|Pharmpy|Xpose4?)([- ](style|format(ted)?))?\\s*", "", x, ignore.case = TRUE, perl = TRUE)
  x <- gsub("\\s+", " ", trimws(x))
  paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))
}
alias_title <- list()
for (rd in db) {
  tags <- vapply(rd, rd_tag, "")
  title <- gsub("\\s+", " ", trimws(rd_text(rd[[which(tags == "\\title")[1]]])))
  for (a in which(tags == "\\alias")) alias_title[[trimws(rd_text(rd[[a]]))]] <- clean_title(title)
}
value_items <- list()
walk_value <- function(x) {
  if (!is.list(x)) return(invisible())
  if (identical(rd_tag(x), "\\item") && length(x) == 2) {
    head <- trimws(rd_text(x[[1]]))
    for (k in trimws(strsplit(head, ",")[[1]])) value_items[[k]] <<- rd_text(x[[2]])
  }
  for (e in x) walk_value(e)
}
fit_rd <- db[["ferx_fit.Rd"]]
walk_value(fit_rd[[which(vapply(fit_rd, rd_tag, "") == "\\value")]])

md_table <- function(df) {
  esc <- function(x) gsub("\n", " ", as.character(x))
  c(paste0("| ", paste(names(df), collapse = " | "), " |"),
    paste0("|", paste(rep("---", ncol(df)), collapse = "|"), "|"),
    apply(df, 1, function(r) paste0("| ", paste(esc(r), collapse = " | "), " |")), "")
}
code <- function(x) paste0("`", x, "`")

# ---- sections -----------------------------------------------------------------------
out <- c(
  "# Function, option and example index {#sec-reference}",
  "",
  "<!-- Generated by tools/make-reference.R from the pinned build. Do not edit by hand. -->",
  "",
  "This chapter lists every ferx-r function, setting, model file block, data column, bundled example, warning category and fit object slot in the pinned build ({{< var ferx_r_sha_short >}}), with the chapter that covers it. It is generated from the book's feature inventory, the package's help pages and the ferx-core documentation of the pinned engine.",
  "")

# Functions
ex <- inv[inv$kind == "export", ]
ex <- ex[order(ex$name), ]
args_of <- function(fn) {
  a <- features$name[features$kind == "argument" & features$parent == fn]
  if (length(a)) paste(code(a), collapse = ", ") else ""
}
fun_tab <- data.frame(
  Function = paste0(code(paste0(ex$name, "()"))),
  Description = vapply(ex$name, function(n) gsub("\\|", "\\\\|", alias_title[[n]] %||% ""), ""),
  Arguments = vapply(ex$name, args_of, ""),
  Chapter = chapter_link(ex$home), check.names = FALSE)
s3 <- inv[inv$kind == "s3method", ]
s3 <- s3[order(s3$name), ]
out <- c(out, "## Functions", "",
  "Help pages: `?name`. Function reference on the web: [ferx-r reference](https://ferx-nlme.github.io/ferx-r/reference/).", "",
  md_table(fun_tab),
  "### S3 methods", "",
  md_table(data.frame(Method = code(s3$name), Chapter = chapter_link(s3$home), check.names = FALSE)))

# Settings
st <- inv[inv$kind == "setting", ]
st <- st[order(st$name), ]
st <- merge(st, settings_docs, by.x = "name", by.y = "key", all.x = TRUE)
st[is.na(st)] <- ""
out <- c(out, "## Fit settings", "",
  "Keys for `ferx_fit(settings = list(...))` and the `[fit_options]` block. Descriptions are in the settings tables of the chapters and on the ferx-core [fit options](https://ferx-nlme.github.io/ferx-core/model-file/fit-options.html) page.", "",
  md_table(data.frame(Setting = code(st$name), Values = gsub("\\|", "\\\\|", st$values),
                      Default = gsub("\\|", "\\\\|", st$default), Chapter = chapter_link(st$home),
                      check.names = FALSE)))

# Model file blocks
block_pages <- c(
  parameters = "model-file/parameters", individual_parameters = "model-file/individual-parameters",
  structural_model = "model-file/structural-model", odes = "model-file/ode-models",
  error_model = "model-file/error-model", fit_options = "model-file/fit-options",
  derived = "model-file/derived", output = "model-file/output", scaling = "model-file/scaling",
  covariates = "model-file/covariates", covariate_model = "model-file/covariate-model",
  covariate_nn = "model-file/covariate-nn", diffusion = "model-file/diffusion",
  event_model = "model-file/event-model", binary_model = "model-file/categorical",
  markov_model = "model-file/markov-model", adaptive_dosing = "model-file/adaptive-dosing",
  data = "model-file/data", data_selection = "model-file/data-selection",
  simulation = "model-file/simulation", initial_conditions = "model-file/initial-conditions",
  mixture = "estimation/mixture")
core_files <- system2("git", c("-C", core_dir, "ls-tree", "-r", "--name-only", pin$ferx_core_sha, "docs"), stdout = TRUE)
bl <- inv[inv$kind == "dsl_block", ]
bl <- bl[order(bl$name), ]
missing_pages <- setdiff(paste0("docs/", block_pages[bl$name], ".qmd"), core_files)
if (length(missing_pages)) stop("ferx-core pages not found at the pin: ", paste(missing_pages, collapse = ", "))
out <- c(out, "## Model file blocks", "",
  md_table(data.frame(Block = code(paste0("[", bl$name, "]")), Chapter = chapter_link(bl$home),
                      `ferx-core page` = sprintf("[%s](https://ferx-nlme.github.io/ferx-core/%s.html)",
                                                 basename(block_pages[bl$name]), block_pages[bl$name]),
                      check.names = FALSE)))

# Data columns
dc <- inv[inv$kind == "data_column", ]
out <- c(out, "## Data columns", "",
  "The full format is on the ferx-core [data format](https://ferx-nlme.github.io/ferx-core/data-format.html) page.", "",
  md_table(data.frame(Column = code(dc$name), Chapter = chapter_link(dc$home), check.names = FALSE)))

# Examples and search files
eg <- inv[inv$kind == "example", ]
eg <- eg[order(eg$name), ]
sf <- inv[inv$kind == "searchfile", ]
out <- c(out, "## Bundled examples", "",
  "Every example is available with `ferx_example()` and its name, which returns the paths of its model and data (and `$search` for a search configuration).", "",
  md_table(data.frame(Example = code(eg$name), Chapter = chapter_link(eg$home), check.names = FALSE)),
  "### Search configurations", "",
  md_table(data.frame(`Example with $search` = code(sf$name), Chapter = chapter_link(sf$home), check.names = FALSE)))

# Warning categories
wc <- inv[inv$kind == "warning_code", ]
wc <- wc[order(wc$name), ]
out <- c(out, "## Warning categories", "",
  "Categories of `ferx_get_warnings(fit, as_df = TRUE)$category`. Each chapter's *Warnings you may see here* section explains the ones it meets; the ferx-core [warnings](https://ferx-nlme.github.io/ferx-core/warnings.html) page describes them all.", "",
  md_table(data.frame(Category = code(wc$name), Chapter = chapter_link(wc$home), check.names = FALSE)))

# Fit slots
fs <- inv[inv$kind == "fit_slot", ]
fs <- fs[order(tolower(fs$name)), ]
out <- c(out, "## Fit object slots", "",
  "Elements of the list `ferx_fit()` returns, for a fit of the warfarin example. Some slots are `NULL` unless the corresponding step or model feature is used. Descriptions are the first sentence of the entry in `?ferx_fit`, where it has one.", "",
  md_table(data.frame(Slot = code(fs$name),
                      Description = vapply(fs$name, function(n) if (is.null(value_items[[n]])) "" else first_sentence(value_items[[n]]), ""),
                      check.names = FALSE)))

# Not available from R
na_tab <- data.frame(
  Feature = c("Variational inference as `ferx_fit(method = \"vi\")`",
              "`[markov_model]` (continuous-time Markov endpoints)",
              "IIV and IOV structure searches, the automatic model-development pipeline, global search",
              "`[simulation]` block",
              "`[dynamics_nn]` (neural-network ODE terms)",
              "Hand-written `[covariate_model]` relations, repeated time-to-event, fixed-rate infusions into the central compartment",
              "`[mixture]` models, modelled infusion rate or duration (`RATE = -1`, `-2`)",
              "VI's ELBO and per-subject posterior summaries"),
  `Status at the pinned build` = c(
    "The `method` argument rejects it; `method = vi` in `[fit_options]` runs",
    "Rejected at parse time: ferx-r does not build the engine's `markov` feature",
    "ferx-core command line only",
    "Read by the ferx-core command line only; ferx-r's simulation functions need a dataset",
    "Not implemented (design only)",
    "Fit from R, but no bundled ferx-r example",
    "No bundled example",
    "Not on the R fit object"),
  `Where to look` = c("@sec-estimation-methods",
                      "[Markov models](https://ferx-nlme.github.io/ferx-core/model-file/markov-model.html)",
                      "@sec-model-selection",
                      "@sec-simulation",
                      "[Neural networks](https://ferx-nlme.github.io/ferx-core/model-file/neural-networks.html)",
                      "@sec-covariates, @sec-time-to-event, @sec-dosing",
                      "@sec-variability, [data format](https://ferx-nlme.github.io/ferx-core/data-format.html)",
                      "[Variational inference](https://ferx-nlme.github.io/ferx-core/estimation/vi.html)"),
  check.names = FALSE)
out <- c(out, "## Not available from R", "",
  "Features documented for ferx-core that the pinned ferx-r build cannot run, or runs only partly:", "",
  md_table(na_tab))

# Maturity
mat <- system2("git", c("-C", core_dir, "show", paste0(pin$ferx_core_sha, ":docs/maturity.qmd")), stdout = TRUE)
rows <- grep("^\\| .* \\| \\*\\*(stable|beta|experimental|alpha)\\*\\* \\|", mat, value = TRUE)
split_row <- function(line) {
  chars <- strsplit(line, "")[[1]]; cells <- character(); cur <- ""; in_code <- FALSE
  for (ch in chars) {
    if (ch == "`") in_code <- !in_code
    if (ch == "|" && !in_code) { cells <- c(cells, cur); cur <- "" } else cur <- paste0(cur, ch)
  }
  trimws(c(cells, cur)[-1])
}
mat_rows <- do.call(rbind, lapply(rows, function(r) {
  cells <- split_row(r)
  page <- sub(".*\\]\\(([^)]+)\\.qmd[^)]*\\).*", "\\1", cells[3])
  label <- sub(".*\\[([^]]+)\\].*", "\\1", cells[3])
  data.frame(Feature = cells[1], Maturity = gsub("\\*", "", cells[2]),
             `ferx-core page` = if (grepl("\\.qmd", cells[3])) sprintf("[%s](https://ferx-nlme.github.io/ferx-core/%s.html)", label, page) else "",
             check.names = FALSE)
}))
mat_rows <- mat_rows[!grepl(banned, mat_rows$Feature, ignore.case = TRUE), ]
out <- c(out, "## Feature maturity", "",
  "The maturity label of each ferx-core feature at the pinned engine (ferx-core {{< var ferx_core_sha_short >}}). **stable** features are well tested across datasets and estimation options; **beta** features are stable in limited testing; **experimental** features have been tested on a few examples and may change. See the ferx-core [feature maturity](https://ferx-nlme.github.io/ferx-core/maturity.html) page.", "",
  md_table(mat_rows))

writeLines(out, "chapters/25-reference.qmd")
cat(sprintf("wrote chapters/25-reference.qmd (%d lines)\n", length(out)))
